### ISSUE TITLE
初始化之后启动 dev server 报错

### ISSUE THREAD

**Issue by zoe0316** [heyui/hey-cli#1]
➜  node -v
v7.10.0
➜  npm -v
4.2.0
➜  hey -v
0.0.26

➜  hey init vue xman_ui
➜  hey dev
```
/usr/local/lib/node_modules/hey-cli/src/generatorWebpackConfig.js:114
      new webpack.LoaderOptionsPlugin({
      ^

TypeError: webpack.LoaderOptionsPlugin is not a constructor
    at initDefaultWebpackConf (/usr/local/lib/node_modules/hey-cli/src/generatorWebpackConfig.js:114:7)
    at module.exports (/usr/local/lib/node_modules/hey-cli/src/generatorWebpackConfig.js:300:20)
    at module.exports (/usr/local/lib/node_modules/hey-cli/src/config.js:62:21)
    at Object.dev (/usr/local/lib/node_modules/hey-cli/src/task.js:16:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/hey-cli/bin/hey-dev.js:30:6)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3
```

**Comment by zoe0316** [comment]
uninstall hey-cli 之后重新安装问题消失.
